/*
  MNT Reform 2.0 Keyboard Firmware
  See keyboard.c for Copyright
  SPDX-License-Identifier: MIT
*/

#include "keyboard.h"

// Every line of `matrix` is a row of the keyboard, starting from the top.
// Check keyboard.h for the definitions of the default rows.
uint8_t matrix[KBD_MATRIX_SZ] = {
  MATRIX_DEFAULT_ROW_1,
  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX_DEFAULT_ROW_4,
  MATRIX_DEFAULT_ROW_5,

  // Custom row six
  HID_KEYBOARD_SC_LEFT_CONTROL,
  HID_KEYBOARD_SC_LEFT_ALT,
  HID_KEYBOARD_SC_LEFT_GUI,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  HID_KEYBOARD_SC_RIGHT_ALT,
  HID_KEYBOARD_SC_EXECUTE,
  HID_KEYBOARD_SC_LEFT_ARROW,
  HID_KEYBOARD_SC_DOWN_ARROW,
  HID_KEYBOARD_SC_RIGHT_ARROW,

  // Marker for layout editor (FIXME)
  KBD_EDITOR_MARKER
};

// When holding down HYPER
uint8_t matrix_fn[KBD_MATRIX_SZ] = {
  // Custom top row
  KEY_ESCAPE,
  KEY_F1,
  KEY_F2,
  KEY_F3,
  KEY_F4,
  KEY_F5,
  KEY_F6,
  HID_KEYBOARD_SC_MEDIA_BACKWARD,
  HID_KEYBOARD_SC_MEDIA_PLAY,
  HID_KEYBOARD_SC_MEDIA_FORWARD,
  HID_KEYBOARD_SC_MEDIA_MUTE,
  HID_KEYBOARD_SC_MEDIA_VOLUME_DOWN,
  HID_KEYBOARD_SC_MEDIA_VOLUME_UP,
  KEY_CIRCLE,

  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX_DEFAULT_ROW_4,

  // Custom row 5
  HID_KEYBOARD_SC_LEFT_SHIFT,
  HID_KEYBOARD_SC_NON_US_BACKSLASH_AND_PIPE,
  KEY_Z,
  KEY_X,
  KEY_C,
  KEY_V,
  KEY_B,
  KEY_N,
  KEY_M,
  HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN,
  HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN,
  KEY_SLASH_AND_QUESTION_MARK,
  HID_KEYBOARD_SC_PAGE_UP,
  HID_KEYBOARD_SC_RIGHT_SHIFT,

  // Custom row 6
  HID_KEYBOARD_SC_LEFT_CONTROL,
  HID_KEYBOARD_SC_LEFT_ALT,
  HID_KEYBOARD_SC_LEFT_GUI,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  HID_KEYBOARD_SC_RIGHT_ALT,
  HID_KEYBOARD_SC_EXECUTE,
  HID_KEYBOARD_SC_HOME,
  HID_KEYBOARD_SC_PAGE_DOWN,
  HID_KEYBOARD_SC_END
};

// Second layer (toggled by HYPER+CIRCLE)
uint8_t matrix_fn_toggled[KBD_MATRIX_SZ] = {
  // Custom top row
  KEY_ESCAPE,
  KEY_F1,
  KEY_F2,
  KEY_F3,
  KEY_F4,
  KEY_F5,
  KEY_F6,
  HID_KEYBOARD_SC_MEDIA_BACKWARD,
  HID_KEYBOARD_SC_MEDIA_PLAY,
  HID_KEYBOARD_SC_MEDIA_FORWARD,
  HID_KEYBOARD_SC_MEDIA_MUTE,
  HID_KEYBOARD_SC_MEDIA_VOLUME_DOWN,
  HID_KEYBOARD_SC_MEDIA_VOLUME_UP,
  KEY_CIRCLE,

  MATRIX_DEFAULT_ROW_2,
  MATRIX_DEFAULT_ROW_3,
  MATRIX_DEFAULT_ROW_4,
  MATRIX_DEFAULT_ROW_5,

  // Custom row six
  HID_KEYBOARD_SC_LEFT_CONTROL,
  HID_KEYBOARD_SC_LEFT_ALT,
  HID_KEYBOARD_SC_LEFT_GUI,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  KEY_SPACE,
  HID_KEYBOARD_SC_RIGHT_ALT,
  HID_KEYBOARD_SC_EXECUTE,
  HID_KEYBOARD_SC_LEFT_ARROW,
  HID_KEYBOARD_SC_DOWN_ARROW,
  HID_KEYBOARD_SC_RIGHT_ARROW
};
